wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700511241.8045
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 77
      2:
      - 1
      - 11
      - 49
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.10.10
      5: 0.15.4
      6: 4.33.2
      8:
      - 1
      - 3
      - 5
